server:
  port: 8888
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 10s
    threads:
      max: 100
      min-spare: 5

spring:
  application:
    name: my-shoppingapp-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arunpatilgithub/my-shoppingapp-config
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
